INSERT INTO USERS (USERNAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('User 1', 'City 1', 'State 1', '12345', TRUE, FALSE, TRUE);

INSERT INTO USERS (USERNAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('User 2', 'City 2', 'State 2', '23456', FALSE, TRUE, FALSE);

INSERT INTO USERS (USERNAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('User 3', 'City 3', 'State 3', '34567', TRUE, FALSE, FALSE);

INSERT INTO USERS (USERNAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('User 4', 'City 4', 'State 4', '45678', FALSE, FALSE, TRUE);

INSERT INTO USERS (USERNAME, CITY, STATE, ZIP_CODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY) VALUES ('User 5', 'City 5', 'State 5', '56789', TRUE, TRUE, TRUE);